### ISSUE TITLE
Add Highlight.scm

### ISSUE THREAD

**Issue by Vixea** [theHamsta/tree-sitter-glsl#11]
It should be pretty close to what's on the c version just remove some and add some more.

**Comment by theHamsta** [comment]
What are you using the queries for? https://github.com/Vixea/tree-sitter-glsl/commit/bbdbcd195ea6683c0e8dfa97cce3cac91d3e6bc8

I'm maintaining the highlight queries for nvim-treesitter (https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/glsl/highlights.scm) but I would not know for which editor or which tree-sitter-cli I would target highlights.scm in this repository.

**Comment by Vixea** [comment]
Lapce, I'm planning on adding glsl support in lapce.

**Comment by theHamsta** [comment]
What captures does lapce support? Is there a list or some hint in the tree-sitter documentation?

Please note that the queries in nvim-treesitter get automatically appended to the C queries (triggered by the magic comment at the beginning of the file)

**Comment by Vixea** [comment]
https://github.com/lapce/lapce/pull/1472
This is a good example, though if you need more I can do so.

**Comment by Vixea** [comment]
@theHamsta ping

**Comment by theHamsta** [comment]
Sorry, I didn't see this and was on holiday the past few weeks. I will have a look into this tomorrow

**Comment by Vixea** [comment]
Thanks

**Comment by theHamsta** [comment]
Ah, now I understand. You want to have the highlight query exposed via the Rust package. I would suggest to use a similar strategy that I did in https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/glsl/highlights.scm . You can use the queries from `tree_sitter_c::HIGHLIGHT_QUERY` and concatenate a modified version of https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/glsl/highlights.scm . tree-sitter-glsl automatically stays up to date with the newest version of tree-sitter-c. So to have consistent highlights with C. It would be easiest to just re-use their queries.

I can probably do that here in this repo. To have `tree_sitter_glsl::HIGHLIGHT_QUERY` be `tree_sitter_c::HIGHLIGHT_QUERY` + https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/glsl/highlights.scm. I would have to do this somehow in the build script, since I don't want to introduce a compile dependency of tree_sitter_c.
