### ISSUE TITLE
Filetypes frag and vert not recognized

### ISSUE THREAD

**Issue by linusvdv** [theHamsta/tree-sitter-glsl#42]
![image](https://github.com/theHamsta/tree-sitter-glsl/assets/30822552/7f7a83ff-cf0f-40d0-a17b-b2c8ebee34e0)
[Left .frag shader and right the same code as .glsl]
The file extensions .frag and .vert are not recognized by tree-sitter-glsl.

I use
```.lua
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all" (the five listed parsers should always be installed)
  ensure_installed = { "javascript", "typescript", "c", "lua", "vim", "vimdoc", "query", "cpp", "glsl"},

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,

  -- Automatically install missing parsers when entering buffer
  -- Recommendation: set to false if you don't have `tree-sitter` CLI installed locally
  auto_install = true,

  highlight = {
    enable = true,

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
```

**Comment by theHamsta** [comment]
`.frag`/`, `.vert` were part of nvim-treesitters configuration before. But they were removed because there were misdetection with other file formats that were using these extensions.

nvim-treesitter now has removed all filetype detections and someone has apparently opened a PR to github.com/vim/vim and then ported to Neovim (https://github.com/neovim/neovim/blob/de28a0f84c577e264f37cd001b03d640db7d5ef9/runtime/lua/vim/filetype.lua#L462) to only detect `.glsl` as  GLSL. If you want to change this logic please submit a PR to github.com/vim/vim or add a filetype detection to your personal config. I personally have
```
    au! BufRead,BufNewFile *.vert,*.frag,*.comp,*.rchit,*.rmiss,*.rahit set filetype=glsl
```
